### PR TITLE
Fix Atom XHTML content type Read/Write in regards to Atom spec.

### LINKED ISSUE #6: IAtomEntry.Description is null for Atom entries with xhtml and */xml content types
I tried to read a sample feed with one entry from https://tools.ietf.org/html/rfc4287#section-1.1 (second sample) and Description field of the read Atom entry was null. As far as I understand this field must contant text representation of the xhtml content without wrapper div. I tried to do the same for application/xml content type and the result was the same - Description field was null.

Repro:
```
static void AtomTest()
{
    var xhtml = "<feed xmlns=\"http://www.w3.org/2005/Atom\"><title type=\"text\">dive into mark</title><subtitle type=\"html\">A &lt;em&gt;lot&lt;/em&gt; of effort went into making this effortless</subtitle><updated>2005-07-31T12:29:29Z</updated><id>tag:example.org,2003:3</id><link rel=\"alternate\" type=\"text/html\" hreflang=\"en\" href=\"http://example.org/\"/><link rel=\"self\" type=\"application/atom+xml\" href=\"http://example.org/feed.atom\"/><rights>Copyright (c) 2003, Mark Pilgrim</rights><generator uri=\"http://www.example.com/\" version=\"1.0\">Example Toolkit</generator><entry><title>Atom draft-07 snapshot</title><link rel=\"alternate\" type=\"text/html\" href=\"http://example.org/2005/04/02/atom\"/><link rel=\"enclosure\" type=\"audio/mpeg\" length=\"1337\" href=\"http://example.org/audio/ph34r_my_podcast.mp3\"/><id>tag:example.org,2003:3.2397</id><updated>2005-07-31T12:29:29Z</updated><published>2003-12-13T08:29:29-04:00</published><author><name>Mark Pilgrim</name><uri>http://example.org/</uri><email>f8dy@example.com</email></author><contributor><name>Sam Ruby</name></contributor><contributor><name>Joe Gregorio</name></contributor><content type=\"xhtml\" xml:lang=\"en\" xml:base=\"http://diveintomark.org/\"><div xmlns=\"http://www.w3.org/1999/xhtml\"><p><i>[Update: The Atom draft is finished.]</i></p></div></content></entry></feed>";

    var feed = new List<object>();

    var byteArray = Encoding.UTF8.GetBytes(xhtml);

    using (var stream = new MemoryStream(byteArray))
    using (var xmlReader = XmlReader.Create(stream, new XmlReaderSettings { CloseInput = true }))
    {
        var feedReader = new AtomFeedReader(xmlReader);

        while (feedReader.Read().Result)
        {
            switch (feedReader.ElementType)
            {
                case SyndicationElementType.Category:
                    ISyndicationCategory category = feedReader.ReadCategory().Result;
                    feed.Add(category);
                    break;

                //
                // Read image
                case SyndicationElementType.Image:
                    ISyndicationImage image = feedReader.ReadImage().Result;
                    feed.Add(image);
                    break;

                //
                // Read entry 
                case SyndicationElementType.Item:
                    IAtomEntry entry = feedReader.ReadEntry().Result;
                    feed.Add(entry);
                    break;

                //
                // Read link
                case SyndicationElementType.Link:
                    ISyndicationLink link = feedReader.ReadLink().Result;
                    feed.Add(link);
                    break;

                //
                // Read person
                case SyndicationElementType.Person:
                    ISyndicationPerson person = feedReader.ReadPerson().Result;
                    feed.Add(person);
                    break;

                //
                // Read content
                default:
                    ISyndicationContent content = feedReader.ReadContent().Result;
                    feed.Add(content);
                    break;
            }
        }
    }

    var description = ((ISyndicationItem) feed[8]).Description; // feed[8] is the entry and description is null
}
```

### PR DESCRIPTION
**Pull request by drago-draganov**
Fixes #6

### CODE REVIEW

File: src/Utils/XmlExtentions.cs [hunk 1]
```diff
@@ -8,68 +8,24 @@ namespace Microsoft.SyndicationFeed
 {
     static class XmlExtentions
     {
-        public static ISyndicationContent ReadSyndicationContent(this XmlReader reader)
+        public static ISyndicationAttribute ReadSyndicationAttribute(this XmlReader reader)
         {
-            var content = new SyndicationContent(reader.Name, reader.NamespaceURI, null);
```
Comment (jimmyca15) [inline src/Utils/XmlExtentions.cs]: Should this check to see if the reader is on an attribute node?

File: src/Atom/AtomConstants.cs [hunk 2]
```diff
@@ -7,8 +7,10 @@ namespace Microsoft.SyndicationFeed.Atom
     static class AtomConstants
     {
         public const string Atom10Namespace = "http://www.w3.org/2005/Atom";
+        public const string XhmlNamespace = "http://www.w3.org/1999/xhtml";
```
[the remark this answers is not in the document]
Comment (drago-draganov) [reply src/Atom/AtomConstants.cs]: Yes. It's a typo.

File: src/Utils/XmlExtentions.cs (hunk 1 above)
Comment (drago-draganov) [reply src/Utils/XmlExtentions.cs]: Good catch. Adding a check
